### ISSUE TITLE
Landing Page : Page not found

### ISSUE THREAD

**Issue by jodth07** [4GeeksAcademy/django-rest-hello#4]
Main end point and api end point returns a "Page not found (404)" error, with some instructions below. But the most obvious part is the error, which may lead users to believe they are getting an actual error from loading up the api. 

Optional solution could be to set the endpoints in a more user friendly look.

**Comment by alesanchezr** [comment]
@jodth07 has a point. At the beginning this 404 is not very friendly, nobody reads it. @nachovz  what do you say if we open a discussion on the class to come up with a better 404 for the API?

**Comment by alesanchezr** [comment]
Here is how to change the 404:
https://stackoverflow.com/questions/28367106/django-rest-framework-custom-404-error-page/28371508

But we would have to keep the message somehow. it is very explicit.

**Comment by jodth07** [comment]
Sure thing.

**Comment by jodth07** [comment]
The message is good, it is the error looking and the word 'ERROR' in that yellow bar that throws people off

**Comment by jodth07** [comment]
I realized that the implementation of swagger only works for the home page, but not other pages. for the other pages, the error still shows

**Comment by alesanchezr** [comment]
@jodth07 hey man, may I ask why did you closed this? Is the swagger website now being shown on the boileplate as the default home? @nachovz ?

I think you guys solve it on your local projects but not on the boilerplate.

**Comment by jodth07** [comment]
hah, you are right. after testing this, it is not implemented on here.

**Comment by jodth07** [comment]
Will be Implementing this.
