### ISSUE TITLE
Tutorial links in README not working

### ISSUE THREAD

**Issue by jodth07** [4GeeksAcademy/django-rest-hello#5]
LINKS:

Working with django /admin to create superusers, add models to your admin, etc.
Using the shell to CRUD models, etc.
Working with Migrations for everytime you change your model
Using MySQL insalling and using MySQL in your application.
Using Mongo insalling and using mongo in your application.
Working with OAuth implementing OAuth with the JWT Oauth Toolkit.

**Comment by alesanchezr** [comment]
Hey @jodth07 ! do you want to fix this and do a PR? it's a piece of cake contribution.

**Comment by jodth07** [comment]
sure thing, will work on this as well!

**Comment by alesanchezr** [comment]
Great man, let me know when you finish the PR and I will add you to the contributor's list that we are creating on the readme. We are following the [All Contributors](https://github.com/kentcdodds/all-contributors) specification starting last week.

**Comment by jodth07** [comment]
actually, I just checked, and looks like the links have been fixed.

**Comment by jodth07** [comment]
but double check and see!
